FROM python:3.7-slim-buster

# install libs for OpenCV for the data augmentation step
RUN apt-get update && apt-get install -y libgl1-mesa-dev libgtk2.0-dev
RUN pip3 install turicreate==6.4.1 boto3 imgaug==0.4.0
